server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: z0h2p1x
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para Santander Dev Week - DIO
  version: 1.0