server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://wixqwyalvtqova:0799e1f61e16c7b35c7fa9f8b6fe9804758318438f9538c689b9593b4b8992bd@ec2-23-23-128-222.compute-1.amazonaws.com:5432/de5vi1ccpumhvf
    username: wixqwyalvtqova
    password: 0799e1f61e16c7b35c7fa9f8b6fe9804758318438f9538c689b9593b4b8992bd
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para Santander Dev Week - DIO
  version: 1.0